// Generated by CoffeeScript 1.7.1
(function() {
  var getSession, getSubject;

  this.Active_Brain = {};

  getSession = function() {
    return $.getJSON("/session");
  };

  getSubject = function() {
    return $.getJSON("/subject");
  };

  Active_Brain.teststart = (function(_this) {
    return function() {
      return RAT.start(1, 1).then(function() {
        return ArrowFlanker.start(1, 1);
      }).then(function() {
        return TrailsB.start(1, 1);
      }).then(function() {
        return AST.start(1, 1);
      });
    };
  })(this);

  Active_Brain.start = (function(_this) {
    return function() {
      return getSession().then(function(session) {
        window._session = session.data.ID;
        return getSubject();
      }).then(function(subject) {
        window._subject = subject.data.ID;
        return AST.start(window._session, window._subject).then(function() {
          return ArrowFlanker.start(window._session, window._subject);
        }).then(function() {
          return TrailsB.start(window._session, window._subject);
        }).then(function() {
          return RAT.start(window._session, window._subject);
        });
      });
    };
  })(this);

}).call(this);
