// Generated by CoffeeScript 1.7.1
(function() {
  var getSession, getSubject;

  this.Active_Brain = {};

  getSession = function() {
    return $.ajax({
      url: "/session",
      type: "GET",
      dataType: "application/json"
    });
  };

  getSubject = function() {
    return $.ajax({
      url: "/subject",
      type: "GET",
      dataType: "application/json"
    });
  };

  Active_Brain.teststart = (function(_this) {
    return function() {
      return RAT.start(1, 1).then(function() {
        return ArrowFlanker.start(1, 1);
      }).then(function() {
        return TrailsB.start(1, 1);
      }).then(function() {
        return AST.start(1, 1);
      });
    };
  })(this);

  Active_Brain.start = (function(_this) {
    return function() {
      return getSession().then(function(session) {
        return getSubject();
      }).then(subject)(function() {
        var session, subject;
        session = session.data.ID;
        subject = subject.data.ID;
        return AST.start(session, subject).then(function() {
          return ArrowFlanker.start(session, subject);
        }).then(function() {
          return TrailsB.start(session, subject);
        }).then(function() {
          return RAT.start(session, subject);
        });
      });
    };
  })(this);

}).call(this);
