// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = Psy._;

  this.Done = {};

  this.Done.experiment = {
    Routines: {
      Prelude: {
        Events: {
          1: {
            Text: {
              content: ["You are finished!", "Please raise your hand briefly and await further instructions."],
              fontSize: 20,
              position: "center",
              origin: "center"
            },
            Next: {
              AnyKey: {}
            }
          }
        }
      }
    },
    Flow: function(routines) {
      return {
        1: routines.Prelude
      };
    }
  };

  this.Done.start = (function(_this) {
    return function(subjectNumber, sessionNumber) {
      var pres;
      _this.context = new Psy.createContext();
      _this.context.set("active_brain", true);
      pres = new Psy.Presentation({}, window.Done.experiment, context);
      return pres.start();
    };
  })(this);

}).call(this);
