// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = Psy._;

  this.RAT = {};

  this.RAT.experiment = {
    Define: {
      active_brain: true,
      resultObject: [],
      resultObject2: []
    },
    Routines: {
      Prelude: {
        Events: {
          1: {
            Markdown: {
              url: "./design/RAT_instructions_page1.md"
            },
            Next: {
              AnyKey: {}
            }
          },
          2: {
            Markdown: {
              url: "./design/RAT_instructions_page3.md"
            },
            Next: {
              AnyKey: {}
            }
          }
        }
      },
      Part1: {
        Start: {
          Text: {
            content: "Press any key to start",
            position: "center",
            origin: "center"
          },
          Next: {
            AnyKey: {}
          }
        },
        End: {
          Text: {
            content: ["End of Part 1", "Press any key to continue."],
            position: "center",
            fontSize: 20,
            origin: "center"
          },
          Next: {
            AnyKey: {}
          }
        },
        Trial: function() {
          return {
            Group: {
              1: {
                Question: {
                  x: this.screen.center.x,
                  y: this.screen.center.y,
                  headerSize: "small",
                  origin: "center",
                  width: "66%",
                  question: this.trial.ProblemStim.toUpperCase(),
                  id: "question",
                  type: "multichoice",
                  choices: [this.trial.AnswerStim1, this.trial.AnswerStim2, this.trial.AnswerStim3],
                  react: {
                    change: (function(_this) {
                      return function(el) {
                        _this.context.set("choice", el);
                        return $("#nextbutton").removeClass("disabled");
                      };
                    })(this)
                  }
                }
              },
              2: {
                HtmlButton: {
                  id: "nextbutton",
                  origin: "center",
                  disabled: true,
                  label: "Next",
                  x: "18.5%",
                  y: "42%"
                }
              }
            },
            Next: {
              Receiver: {
                id: "nextbutton",
                signal: "clicked"
              }
            },
            Feedback: function() {
              var correct, resp, resultObj;
              correct = this.context.get("choice") === this.trial.solution;
              resp = {
                questionID: 0,
                answer: this.context.get("choice"),
                correct: correct,
                condition: "Recognition",
                question: this.trial.ProblemStim.toUpperCase(),
                trialNumber: this.context.get("State.trialNumber"),
                blockNumber: this.context.get("State.blockNumber"),
                solution: this.trial.solution,
                Task: "Remote Associates"
              };
              resultObj = this.context.get("resultObject");
              resultObj.push(resp);
              console.log(resultObj);
              return {
                Events: {
                  1: {
                    Text: {
                      content: correct ? "Correct!" : "Incorrect.",
                      origin: "center",
                      position: "center"
                    },
                    Next: {
                      Timeout: {
                        duration: 700
                      }
                    }
                  }
                }
              };
            }
          };
        }
      },
      Part2: {
        Start: {
          Markdown: {
            url: "./design/RAT_instructions_page2.md"
          },
          Next: {
            AnyKey: {}
          }
        },
        End: {
          Text: {
            content: "End of Remote Associates Task. Press any key to continue",
            position: "center",
            origin: "center",
            fontSize: 20
          },
          Next: {
            AnyKey: {}
          }
        },
        Trial: function() {
          var block, context, questions;
          questions = {};
          block = RAT.trialsPart2.getBlock(0);
          context = this.context;
          console.log("context is", this.context);
          console.log("block is", block);
          _.forEach(block, function(record, i) {
            console.log(record);
            return questions[(i + 1).toString()] = {
              Question: {
                x: "5%",
                width: "50%",
                headerSize: "small",
                question: record.Stimulus.toUpperCase(),
                id: "question_" + (i + 1),
                type: "textfield",
                react: {
                  change: function(el) {
                    var index, res, resultObj;
                    resultObj = context.get("resultObject2");
                    index = el.id.split("_")[1];
                    res = {
                      questionID: el.id,
                      answer: el.val,
                      condition: "Generate",
                      question: record.Stimulus.toUpperCase(),
                      trialNumber: index,
                      blockNumber: context.get("State.blockNumber"),
                      solution: record.solution,
                      Task: "Remote Associates"
                    };
                    resultObj[index] = res;
                    return console.log(resultObj);
                  }
                }
              }
            };
          });
          return {
            Group: questions,
            Next: {
              Timeout: {
                duration: 60000
              }
            },
            Feedback: function() {
              return console.log("feedback", this.response);
            }
          };
        }
      },
      Save: function() {
        return {
          Action: {
            execute: function(context) {
              var logdat, logdat1, logdat2;
              if (context.get("active_brain")) {
                logdat1 = context.get("resultObject");
                logdat2 = context.get("resultObject2");
                logdat = logdat1.concat(logdat2);
                console.log("saving ", logdat);
                return $.ajax({
                  type: "POST",
                  url: "/results",
                  data: JSON.stringify(logdat),
                  contentType: "application/json"
                });
              }
            }
          }
        };
      }
    },
    Flow: (function(_this) {
      return function(routines) {
        return {
          1: routines.Prelude,
          2: {
            BlockSequence: {
              start: routines.Part1.Start,
              trialList: _this.RAT.trialsPart1,
              trial: routines.Part1.Trial,
              end: routines.Part1.End
            }
          },
          3: {
            BlockSequence: {
              start: routines.Part2.Start,
              trialList: _this.RAT.dummyTrials,
              trial: routines.Part2.Trial,
              end: routines.Part2.End
            }
          },
          4: routines.Save
        };
      };
    })(this)
  };

  this.RAT.start = (function(_this) {
    return function(sessionNumber, subjectNumber) {
      var design_gen, design_recog, pres;
      if (sessionNumber > 2) {
        sessionNumber = 2;
      }
      design_recog = Psy.loadTable("design/RAT_RecList" + sessionNumber + ".txt", ",");
      design_gen = Psy.loadTable("design/RAT_GenList" + sessionNumber + ".txt", ",");
      _this.RAT.trialsPart1 = Psy.TrialList.fromBlock(design_recog);
      _this.RAT.trialsPart2 = Psy.TrialList.fromBlock(design_gen);
      _this.RAT.dummyTrials = new Psy.TrialList(1);
      _this.RAT.dummyTrials.add(0, {});
      _this.RAT.context = Psy.createContext();
      pres = new Psy.Presentation({}, _this.RAT.experiment, _this.RAT.context);
      return pres.start();
    };
  })(this);

}).call(this);

//# sourceMappingURL=runner.map
